### ISSUE TITLE
the arxiv link for the paper  PLATE

### ISSUE THREAD

**Issue by Lmoer** [Applied-Machine-Learning-Lab/PLATE#1]
Can you provide the arxiv link for the paper  PLATE: A Prompt-Enhanced Paradigm for Multi-Scenario Recommendations？

**Comment by wyhwhy** [comment]
Sorry for the late reply. It was released last month after SIGIR presentation since Huawei's policy.
https://dl.acm.org/doi/10.1145/3539618.3591750
